function post_proc_fig_box

% Code for post processing boxplots
% 
% Written by: Ahmed Abdul Quadeer 
% Last updated: 2018-04-07


set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XColor'      , [.1 .1 .1], ...
    'YColor'      , [.1 .1 .1], ...
    'XTick'       , 1:1:100,... 
    'LineWidth'   , .5        );